# Generated by Django 2.0.6 on 2019-03-01 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_school', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('hours', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('date_worked', models.DateField()),
                ('date_of_entry', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
